# Static Traefik configuration (generated by scripts/03_generate_secrets.sh)
global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

accessLog: {}

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  bolt:
    address: ":7687"

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/traefik.dynamic.yml
    watch: true

certificatesResolvers:
  acme:
    acme:
      email: "${ACME_EMAIL:-}"
      storage: "/acme/acme.json"
      httpChallenge:
        entryPoint: web

serversTransport:
  insecureSkipVerify: true
